config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :users, controllers: { registrations: "registrations"}

  get "/pages/:page" => "pages#show"

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"

    authenticated :user do
      root 'members#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root 'members#index'

end

app/models/belt.rb
class Belt < ActiveRecord::Base

  belongs_to :member

  validates :belt, inclusion: { in: 1..5, message: "must be selected" }
  validates :stripes, inclusion: { in: 0..4, message: "number must be selected" }
  #validates :promotion_date, presence: true

end

app/models/member.rb
class Member < ActiveRecord::Base

  has_many :belts

  validates :first_name, presence: true, length: 0..30
  validates :nickname, length: 0..50
  validates :last_name, presence: true, length: 0..35
  validates :belt, inclusion: { in: 1..5, message: "must be selected" }
  validates :stripes, inclusion: { in: 0..4, message: "number must be selected" }

  mount_uploader :avatar, AvatarUploader

  def fullname
    self.first_name.to_s + " " + self.nickname.to_s + " " + self.last_name.to_s
  end

  def self.search(search)
    #where("first_name LIKE ?", "%#{search}%")
    #where("lower(last_name) LIKE ?", "%#{search}%")
    #where("lower(first_name || ' ' || last_name) like ?", "%#{search}%")
    where("lower(first_name || ' ' || nickname || ' ' || last_name) like ?", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
    if params[:search]
      @members = Member.search(params[:search]).order("#{sort_column} #{sort_direction}")
    else
      @members = Member.order("#{sort_column} #{sort_direction}").order("stripes #{sort_direction}")
    end
  end

  def show
  end

  def new
    @member = Member.new
  end

  def edit
  end

  def create
    @member = Member.new(member_params)

    return render :new unless @member.save
    redirect_to @member, notice: 'Member was successfully created.'
  end

  def update
    return render :edit unless @member.update(member_params)
    redirect_to @member, notice: 'Member was successfully updated.'
  end

  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:first_name, :nickname, :last_name, :date_birth, :date_joined, :belt, :stripes, :avatar, :description)
    end

    def sortable_columns
      ["id", "first_name", "nickname", "last_name", "date_birth", "date_joined", "belt"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def show
    render template: "pages/#{params[:page]}"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :two_users_registered?

  protected

  def two_users_registered?
    if ((User.count == 2) & (user_signed_in?))
      redirect_to root_path
    elsif User.count == 2
      redirect_to new_user_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/members_helper.rb
module MembersHelper
  def sort_link(column, title = nil)
    #title ||= column.titleize
    title ||= Member.human_attribute_name(column).titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end

  def belt_class(belt)
    case belt
    when 1
      "belt-white"
    when 2
      "belt-blue"
    when 3
      "belt-purple"
    when 4
      "belt-brown"
    when 5
      "belt-black"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper

  #to be moved into a presenter
  def belt_count(*belt)
    case belt.count
    when 1
      Member.where(belt: belt[0]).count
    when 2
      Member.where(belt: belt[0], stripes: belt[1]).count
    else
      Member.all.count
    end
  end

  def belt_name(belt)
    case belt
    when 1
      "White"
    when 2
      "Blue"
    when 3
      "Purple"
    when 4
      "Brown"
    when 5
      "Black"
    end
  end

end

app/views/layouts/_belt.html.erb
<div class="<%= belt_class(belt) %>">
  <ul class="patch">
    <% stripes.times do |x| %>
      <li class="stripe"></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="muted credit text-center">Kociamber &copy; <%= Time.now.year %></p>
</footer>

app/views/layouts/_messages.html.erb
<!-- <% if notice %> -->
  <!-- <div class="alert alert-success alert-dismissible" role="alert"> -->
    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <!-- <%= notice %> -->
  <!-- </div> -->
<!-- <% end %> -->
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Gorilaz', root_path, class: 'navbar-brand' %>
      <!-- <%= link_to image_tag('gorila_logo.png', class: "logo"), root_path, class: "navbar-brand" %> -->
    </div>
    <% if user_signed_in? %>
      <div class="navbar-text navbar-left">
        <%= link_to t('Add Member'), new_member_path %>
      </div>
      <div class="navbar-text navbar-left">
        <%= link_to t('Statistics'), '/pages/totals' %>
      </div>
    <% end %>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to(current_user.email, edit_user_registration_path) %></li>
          <li><%= link_to t('Sign out'), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to(t('Sign in'), new_user_session_path) %></li>
          <!-- <li><%= link_to('Sign up', new_user_registration_path) %></li> -->
        <% end %>
      </ul>
      <%= form_tag(members_path, method: :get, id: "search-form", class: "navbar-form navbar-right") do %>
        <%= text_field_tag :search, params[:search], placeholder: t('Person'), class: "form-control" %>
        <%= submit_tag t("Search"), class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_totals.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= t(belt_name(belt)) %>
    <span class="badge belt-badge"><%= belt_count(belt) %></span>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <span class="badge"><%= belt_count(belt, 0) %></span>
      <%= t('Zero stripes') %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= belt_count(belt, 1) %></span>
      <%= t('One stripe') %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= belt_count(belt, 2) %></span>
      <%= t('Two stripes') %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= belt_count(belt, 3) %></span>
      <%= t('Three stripes') %>
    </li>
    <li class="list-group-item">
      <span class="badge"><%= belt_count(belt, 4) %></span>
      <%= t('Four stripes') %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gorilaz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :date_birth %><br>
    <%= f.date_select :date_birth, start_year: 1950, include_blank: true, default: nil, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :date_joined %><br>
    <%= f.date_select :date_joined, start_year: 2005, end_year: Time.now.year, include_blank: true, default: nil, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :belt %><br>
    <%= f.select :belt, [['White','1'],['Blue','2'],['Purple','3'],['Brown','4'],['Black','5']], class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :stripes %><br>
    <%= f.select :stripes, [0,1,2,3,4], class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :avatar %><br>
    <%= image_tag(@member.avatar, class: "avatar") %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<!-- <h3><%= t('Editing Member') %></h3> -->

<%= render 'form' %>
<br/>
<div>
  <%= link_to t('Show'), @member %> |
  <%= link_to t('Back'), members_path %>
</div>
<br/>

app/views/members/index.html.erb
<h2>Academia Gorila <%= Member.model_name.human(count: 2).titleize %></h2>

<div class="row table-header">
  <span class="col-md-4 table-monkey"><%= sort_link "id" %> <%= sort_link "first_name" %> <%= sort_link "last_name" %></span>
  <!-- <span class="col-md-2 table-monkey"><%= sort_link "last_name" %></span> -->
  <span class="col-md-2 table-joined"><%= sort_link "date_joined" %></span>
  <span class="col-md-5 table-belt"><%= sort_link "belt" %></span>
  <span class="col-md-1 table-monkey"><%= t('Description')%></span>
</div>

<% @members.each do |member| %>
  <div class="row table-row">
    <div class="col-md-4 member-name">
      <span class="id"><%= member.id %></span>
      <%= link_to image_tag(member.avatar, class: "avatar_small"), member %><%= link_to member.fullname, member %>
    </div>
    <div class="col-md-2 member-joined">
      <%= member.date_joined %>
    </div>
    <div class="col-md-3 member-belt">
      <%= render partial: 'layouts/belt', locals: {belt: member.belt, stripes: member.stripes} %>
    </div>
    <div class="col-md-2">
      <%= link_to t('Show'), member %> |
      <%= link_to t('Edit'), edit_member_path(member) %> |
      <%= link_to t('Destroy'), member, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div class="col-md-1">
      <% if member.description.present? %>
        <span class="glyphicon glyphicon-ok"></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/members/new.html.erb
<!-- <h4><%= t('New Member') %></h4> -->

<%= render 'form' %>
<br/>
<div>
  <%= link_to t('Back'), members_path %>
</div>
<br/>

app/views/members/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag(@member.avatar, class: "avatar") %>
  </div>
  <div class="col-md-9">
    <div class="row">
      <div class="col-md-12">
        <h3><%= @member.fullname %></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 show-belt">
        <%= render partial: 'layouts/belt', locals: {belt: @member.belt, stripes: @member.stripes} %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <strong><%= t(:Joined) %>:</strong>
        <%= @member.date_joined %>
        <br/>
        <strong><%= t(:Born) %>:</strong>
        <%= @member.date_birth %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <strong><%= t(:Description) %>:</strong>
        <%= @member.description %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= link_to t('Edit'), edit_member_path(@member) %> |
        <%= link_to t('Back'), members_path %>
      </div>
    </div>
  </div>
</div>

app/views/pages/totals.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading"> <%= t('Members total') %>:
        <span class="badge belt-badge"><%= belt_count %></span>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/totals', belt: 1 %>
  </div>
  <div class="col-md-3">
    <%= render 'layouts/totals', belt: 2 %>
  </div>
  <div class="col-md-3">
    <%= render 'layouts/totals', belt: 3 %>
  </div>
  <div class="col-md-3">
    <%= render 'layouts/totals', belt: 4 %>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <%= render 'layouts/totals', belt: 5 %>
  </div>
  <div class="col-md-9">
  </div>
</div>